### ISSUE TITLE
포스트 작성할때 이미지 첨부하면 포스팅 안됨

### ISSUE THREAD

**Issue by hyobbu** [Jw-Bluayer/AmateurStudio#6]
이미지 첨부 없이 제목, 내용만 작성하면 잘됨

**Comment by Jw-Bluayer** [comment]
이미지 첨부 문제
= carrier wave에서 fog aws key의 문제였던 것으로 확인.
aws 서비스 사용자가 bucket이나 credential을 삭제함으로써 생긴 일인듯.
일단 본인의 aws로 연결해둠.
